### ISSUE TITLE
Testar cada perfil

### ISSUE THREAD

**Issue by alecostaweb** [GabrielDully/grafica#4]

**Comment by GabrielDully** [comment]
Boa tarde, Alê!

Essa issue seria para os testes da implementação original da FFLCH, i.e., antes das atualizações referentes às outras issues (e.g., criação do logon para editora e gráfica) ; após nossas alterações; ou ambos?

Os testes dos perfis com a implementação original da FFLCH já foram realizados.

**Comment by alecostaweb** [comment]
Esta issue foi para conhecer o sistema, levantar os erros com e-mails e o que precisa ser generalizado.
Pode fechar.
